services:
  - type: web
    name: scotland-yard-server
    runtime: node
    buildCommand: npm install --prefix server
    startCommand: node server/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
